### ISSUE TITLE
std::__1::regex_error exception is thrown when calling .load

### ISSUE THREAD

**Issue by tiksem** [swesterfeld/liquidsfz#19]
The problem is here:

static const regex define_re ("\\s*#\\s*define\\s+(\\$\\S+*)\\s([^$]*)");
  if (regex_match (line, sm, define_re))
  Line 516, loader.cc
  
I've copied the same regex expression to a separate project and tested and it throws the same error:

libc++abi.dylib: terminating with uncaught exception of type std::__1::regex_error: One of *?+{ was not preceded by a valid regular expression.

I have MacOS 11.0.1, clang version 12.0.0

**Comment by swesterfeld** [comment]
I was able to reproduce this on linux with clang++10 and libc++, indeed the regex did look suspicious. Should be fixed by https://github.com/swesterfeld/liquidsfz/commit/36b77e665a90dd1f66acb00c3f7bcf9df27001de
