### ISSUE TITLE
Tags are missing

### ISSUE THREAD

**Issue by dvzrv** [swesterfeld/liquidsfz#2]
Hi! I would like to be able to package liquidsfz for Arch Linux. To fend off [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack) and be able to reproducibly build liquidsfz, it would be required to tag commits of this repository accordingly, instead of only having a downloadable source tarball, that could contain anything and is not directly linkable to a commit in this repository.

Thanks!

**Comment by swesterfeld** [comment]
Right. I've now pushed the 0.1.0 tag from my private repo. You should be able to build from the tag. Still for end users I'd recommend the tarball I provided, as it contains the make dist step (./configure instead of ./autogen.sh).
