### ISSUE TITLE
Tag for 0.2.2 is missing

### ISSUE THREAD

**Issue by dvzrv** [swesterfeld/liquidsfz#22]
Hi! I would like to package 0.2.2 for Arch Linux.
Unfortunately the tag for 0.2.2 is missing. I use this git repository for my upstream checking to see if there are new versions available and the auto-generated tarballs from this repository to build the package.

Can you push the tag here as well? Is there another git repository, that I should be aware of for upstream tracking? :)

**Comment by swesterfeld** [comment]
Right, i fixed this now: I've pushed the 0.2.2 tag now.

> Is there another git repository, that I should be aware of for upstream tracking? :)

No, I use another repo for development, but I think github is fine for everybody else...
