### ISSUE TITLE
Request for Synth::get_num_used_voices() API

### ISSUE THREAD

**Issue by falkTX** [swesterfeld/liquidsfz#4]
We currently have `Synth::set_max_voices`, but without a way to know the currently in-use number of voices, it is hard to know if there is room for less or not (we need to go by ear)

**Comment by swesterfeld** [comment]
Right, this makes sense: https://github.com/swesterfeld/liquidsfz/commit/7ef8c1200589d14856422faf30b6c544f10b6560
