### ISSUE TITLE
lv2 plugin lacks full RELRO

### ISSUE THREAD

**Issue by dvzrv** [swesterfeld/liquidsfz#5]
When building 0.2.0 for Arch Linux I realized, that the lv2 plugin Makefile doesn't make use of the general `LDFLAGS` and therefore lacks full RELRO.

I can open a pull request to fix this.

**Comment by swesterfeld** [comment]
Fixed via https://github.com/swesterfeld/liquidsfz/commit/94c0e4b3986e652f0e1bbab4dcc9772b6c991c11
