### ISSUE TITLE
Enable compiling (also) against shared library

### ISSUE THREAD

**Issue by dvzrv** [swesterfeld/liquidsfz#7]
The static-only library approach is not very useful in a packaging environment.
It would be awesome, if liquidsfz (and the lv2 plugin) could be compiled either against a static or a shared library.

The current setup ignores the `--enable-shared`/ `--disable-static` settings and always compiles against the static library.

**Comment by swesterfeld** [comment]
This might be a bit of a discussion, the static library was a design decision.

Ok, here is one example what goes wrong with dynamic linking. Suppose you get a host as AppImage. Of course that host dynamically links all kinds of libs. Now you have a LV2 plugin from your distribution. Dynamically linked as you want to. For this example, lets assume both link against libliquidsfz.so.

Then it can happen that the host forces an incompatible liquidsfz onto the LV2 plugin, and anything can happen. I've seen this with SpectMorph and AppImages for LMMS.

Now suppose liquidsfz was a header-only library. The host would #include <liquidsfz.hh> and the LV2 plugin would #include <liquidsfz.hh>. The plugin would not export any symbols. Now everything works fine, as the host and the LV2 plugin have their own self-contained liquidsfz.hh code.

What I'm trying to do here is get this behaviour by default. So everything behaves as-if liquidsfz would be a header only library. And you do package such libraries (see boost). So I just suggest that the distribution should treat liquidsfz as it treats boost. Including a copy in each application or plugin that needs it. This also means that we don't need to maintain ABI compatibility, as long as an application compiles, it will also work. And there is no way of breaking an application by updating a shared liquidsfz.so library that doesn't have the same ABI.

I think this is bit of a mess under linux, under windows you just build your plugin as DLL and link it statically and it will just work on any windows with any host always. LV2 conceptually requires you to do completely self-contained plugins, and liquidsfz only does this if you use the static/build.sh which does a docker build. The resulting binary has almost no dependencies, so this is a bit like the windows case. But the more dynamic linking you do, the more things can break.

**Comment by swesterfeld** [comment]
I've added support in liquidsfz 0.2.1 for shared libraries (--enable-shared), even though I still believe the safer choice is using static libs only. But you as packager can choose now whether or not you build shared libs. So I'm closing the issue now.
