### ISSUE TITLE
File extension in LV2

### ISSUE THREAD

**Issue by iurienistor** [swesterfeld/liquidsfz#9]
When opening the browse file dialog for LV2 there are shown all types of files. Is there a possibility to filter only *.sfz?

**Comment by swesterfeld** [comment]
The lv2 ui is a generic ui generated by the host. The file dialog is shown by the host, in the .ttl file it looks like
```
<http://spectmorph.org/plugins/liquidsfz#sfzfile>
  a lv2:Parameter;
  rdfs:label "SFZ File";
  rdfs:range atom:Path .
[...]
  patch:writable <http://spectmorph.org/plugins/liquidsfz#sfzfile>;
```
As far as I know there is no way to specify filters or extensions here.

**Comment by swesterfeld** [comment]
I'm closing this issue, as I see no way to implement an extension filter here. Btw, it would have to be .sfz/.xml due to hydrogen support these days.
